apiVersion: apps/v1
kind: Deployment
metadata:
  name: mynodeapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mynodeapp
  template:
    metadata:
      labels:
        app: mynodeapp
    spec:
      containers:
        - name: mynodeapp
          # Usa la imagen con la "nueva" etiqueta si quieres
          image: ghcr.io/gotohola/mynodeapp:redis
          env:
            - name: REDIS_HOST
              value: "redis-service"
          ports:
            - containerPort: 3000
