apiVersion: v1
kind: Service
metadata:
  name: mynodeapp
spec:
  type: NodePort
  selector:
    app: mynodeapp
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
      nodePort: 30080
